# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Repositories\lang_tutor\modules\module_kanji\editor\kanji_block_view.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(460, 660)
        self.gridLayout_3 = QtWidgets.QGridLayout(Form)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.kanjiContainer = QtWidgets.QWidget(Form)
        self.kanjiContainer.setEnabled(True)
        self.kanjiContainer.setObjectName("kanjiContainer")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.kanjiContainer)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.kanjiContainer)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setHorizontalSpacing(12)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.kanjiLnEd = QtWidgets.QLineEdit(self.kanjiContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.kanjiLnEd.sizePolicy().hasHeightForWidth())
        self.kanjiLnEd.setSizePolicy(sizePolicy)
        self.kanjiLnEd.setMinimumSize(QtCore.QSize(150, 150))
        self.kanjiLnEd.setMaximumSize(QtCore.QSize(150, 150))
        font = QtGui.QFont()
        font.setFamily("Yu Mincho")
        font.setPointSize(32)
        self.kanjiLnEd.setFont(font)
        self.kanjiLnEd.setMaxLength(1)
        self.kanjiLnEd.setAlignment(QtCore.Qt.AlignCenter)
        self.kanjiLnEd.setObjectName("kanjiLnEd")
        self.gridLayout_2.addWidget(self.kanjiLnEd, 0, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(12)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_7 = QtWidgets.QLabel(self.kanjiContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_4.addWidget(self.label_7)
        self.keyCmbBx = QtWidgets.QComboBox(self.kanjiContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.keyCmbBx.sizePolicy().hasHeightForWidth())
        self.keyCmbBx.setSizePolicy(sizePolicy)
        self.keyCmbBx.setObjectName("keyCmbBx")
        self.horizontalLayout_4.addWidget(self.keyCmbBx)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.kanjiContainer)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.dashCountSpBx = QtWidgets.QSpinBox(self.kanjiContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dashCountSpBx.sizePolicy().hasHeightForWidth())
        self.dashCountSpBx.setSizePolicy(sizePolicy)
        self.dashCountSpBx.setObjectName("dashCountSpBx")
        self.horizontalLayout_3.addWidget(self.dashCountSpBx)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_2)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(-1, 10, -1, 10)
        self.gridLayout.setHorizontalSpacing(10)
        self.gridLayout.setVerticalSpacing(20)
        self.gridLayout.setObjectName("gridLayout")
        self.label_4 = QtWidgets.QLabel(self.kanjiContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.kanjiContainer)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 3, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.kanjiContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 2, 2, 1, 1)
        self.onReadingPte = QtWidgets.QPlainTextEdit(self.kanjiContainer)
        self.onReadingPte.setTabChangesFocus(True)
        self.onReadingPte.setObjectName("onReadingPte")
        self.gridLayout.addWidget(self.onReadingPte, 1, 3, 1, 1)
        self.kunReadingPte = QtWidgets.QPlainTextEdit(self.kanjiContainer)
        self.kunReadingPte.setTabChangesFocus(True)
        self.kunReadingPte.setObjectName("kunReadingPte")
        self.gridLayout.addWidget(self.kunReadingPte, 2, 3, 1, 1)
        self.translatePte = QtWidgets.QPlainTextEdit(self.kanjiContainer)
        self.translatePte.setTabChangesFocus(True)
        self.translatePte.setObjectName("translatePte")
        self.gridLayout.addWidget(self.translatePte, 3, 3, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.gridLayout_3.addWidget(self.kanjiContainer, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "KANJI_LBL"))
        self.label_7.setText(_translate("Form", "KEY_LBL"))
        self.label_3.setText(_translate("Form", "DASH_COUNT_LBL"))
        self.label_4.setText(_translate("Form", "ON_LBL"))
        self.label_6.setText(_translate("Form", "TRANSLATE_LBL"))
        self.label_5.setText(_translate("Form", "KUN_LBL"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
