# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Repositories\lang_tutor\ui\main\main_view.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1024, 768)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.menuLayout = QtWidgets.QVBoxLayout()
        self.menuLayout.setSpacing(15)
        self.menuLayout.setObjectName("menuLayout")
        self.label = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.menuLayout.addWidget(self.label)
        self.scenarioMenuBtn = QtWidgets.QPushButton(Form)
        self.scenarioMenuBtn.setCheckable(False)
        self.scenarioMenuBtn.setObjectName("scenarioMenuBtn")
        self.menuLayout.addWidget(self.scenarioMenuBtn)
        self.editorMenuBtn = QtWidgets.QPushButton(Form)
        self.editorMenuBtn.setEnabled(True)
        self.editorMenuBtn.setObjectName("editorMenuBtn")
        self.menuLayout.addWidget(self.editorMenuBtn)
        self.modulesMenuBtn = QtWidgets.QPushButton(Form)
        self.modulesMenuBtn.setCheckable(False)
        self.modulesMenuBtn.setObjectName("modulesMenuBtn")
        self.menuLayout.addWidget(self.modulesMenuBtn)
        self.configMenuBtn = QtWidgets.QPushButton(Form)
        self.configMenuBtn.setEnabled(True)
        self.configMenuBtn.setObjectName("configMenuBtn")
        self.menuLayout.addWidget(self.configMenuBtn)
        self.debugMenuBtn = QtWidgets.QPushButton(Form)
        self.debugMenuBtn.setObjectName("debugMenuBtn")
        self.menuLayout.addWidget(self.debugMenuBtn)
        self.quitMenuBtn = QtWidgets.QPushButton(Form)
        self.quitMenuBtn.setObjectName("quitMenuBtn")
        self.menuLayout.addWidget(self.quitMenuBtn)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.menuLayout.addItem(spacerItem)
        self.gridLayout.addLayout(self.menuLayout, 0, 0, 1, 1)
        self.stackedWidget = QtWidgets.QStackedWidget(Form)
        self.stackedWidget.setObjectName("stackedWidget")
        self.commingSoonPage = QtWidgets.QWidget()
        self.commingSoonPage.setObjectName("commingSoonPage")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.commingSoonPage)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_2 = QtWidgets.QLabel(self.commingSoonPage)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.commingSoonPage)
        self.scenarioPage = QtWidgets.QWidget()
        self.scenarioPage.setObjectName("scenarioPage")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.scenarioPage)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_3 = QtWidgets.QLabel(self.scenarioPage)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 0, 1, 1)
        self.scenarioListRefreshBtn = QtWidgets.QPushButton(self.scenarioPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scenarioListRefreshBtn.sizePolicy().hasHeightForWidth())
        self.scenarioListRefreshBtn.setSizePolicy(sizePolicy)
        self.scenarioListRefreshBtn.setMinimumSize(QtCore.QSize(125, 25))
        self.scenarioListRefreshBtn.setObjectName("scenarioListRefreshBtn")
        self.gridLayout_2.addWidget(self.scenarioListRefreshBtn, 0, 1, 1, 1)
        self.scenarioList = QtWidgets.QListWidget(self.scenarioPage)
        self.scenarioList.setObjectName("scenarioList")
        self.gridLayout_2.addWidget(self.scenarioList, 1, 0, 1, 2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.starScenarioBtn = QtWidgets.QPushButton(self.scenarioPage)
        self.starScenarioBtn.setObjectName("starScenarioBtn")
        self.horizontalLayout.addWidget(self.starScenarioBtn)
        self.optionsEnableChbx = QtWidgets.QCheckBox(self.scenarioPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.optionsEnableChbx.sizePolicy().hasHeightForWidth())
        self.optionsEnableChbx.setSizePolicy(sizePolicy)
        self.optionsEnableChbx.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.optionsEnableChbx.setObjectName("optionsEnableChbx")
        self.horizontalLayout.addWidget(self.optionsEnableChbx)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 1)
        self.horizontalLayout.setStretch(2, 1)
        self.gridLayout_2.addLayout(self.horizontalLayout, 2, 0, 1, 2)
        self.stackedWidget.addWidget(self.scenarioPage)
        self.modulesPage = QtWidgets.QWidget()
        self.modulesPage.setObjectName("modulesPage")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.modulesPage)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_4 = QtWidgets.QLabel(self.modulesPage)
        self.label_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_4.addWidget(self.label_4, 0, 0, 1, 1)
        self.modulesListRefreshBtn = QtWidgets.QPushButton(self.modulesPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.modulesListRefreshBtn.sizePolicy().hasHeightForWidth())
        self.modulesListRefreshBtn.setSizePolicy(sizePolicy)
        self.modulesListRefreshBtn.setMinimumSize(QtCore.QSize(125, 25))
        self.modulesListRefreshBtn.setObjectName("modulesListRefreshBtn")
        self.gridLayout_4.addWidget(self.modulesListRefreshBtn, 0, 1, 1, 1)
        self.modulesList = QtWidgets.QListWidget(self.modulesPage)
        self.modulesList.setObjectName("modulesList")
        self.gridLayout_4.addWidget(self.modulesList, 3, 0, 1, 2)
        self.stackedWidget.addWidget(self.modulesPage)
        self.debugPage = QtWidgets.QWidget()
        self.debugPage.setObjectName("debugPage")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.debugPage)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.logPte = QtWidgets.QPlainTextEdit(self.debugPage)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.logPte.setFont(font)
        self.logPte.setReadOnly(True)
        self.logPte.setPlainText("")
        self.logPte.setObjectName("logPte")
        self.gridLayout_5.addWidget(self.logPte, 1, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.debugPage)
        self.label_5.setObjectName("label_5")
        self.gridLayout_5.addWidget(self.label_5, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.debugPage)
        self.editorPage = QtWidgets.QWidget()
        self.editorPage.setObjectName("editorPage")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.editorPage)
        self.gridLayout_6.setContentsMargins(-1, 50, -1, 100)
        self.gridLayout_6.setObjectName("gridLayout_6")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem2, 0, 2, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem3, 0, 0, 1, 1)
        self.verticalGroupBox = QtWidgets.QGroupBox(self.editorPage)
        self.verticalGroupBox.setObjectName("verticalGroupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalGroupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.createNewRbn = QtWidgets.QRadioButton(self.verticalGroupBox)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.createNewRbn.setFont(font)
        self.createNewRbn.setChecked(True)
        self.createNewRbn.setObjectName("createNewRbn")
        self.verticalLayout.addWidget(self.createNewRbn)
        self.createFromRbn = QtWidgets.QRadioButton(self.verticalGroupBox)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.createFromRbn.setFont(font)
        self.createFromRbn.setObjectName("createFromRbn")
        self.verticalLayout.addWidget(self.createFromRbn)
        self.createFromList = QtWidgets.QListWidget(self.verticalGroupBox)
        self.createFromList.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.createFromList.setObjectName("createFromList")
        self.verticalLayout.addWidget(self.createFromList)
        self.loadRbn = QtWidgets.QRadioButton(self.verticalGroupBox)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.loadRbn.setFont(font)
        self.loadRbn.setObjectName("loadRbn")
        self.verticalLayout.addWidget(self.loadRbn)
        self.loadList = QtWidgets.QListWidget(self.verticalGroupBox)
        self.loadList.setObjectName("loadList")
        self.verticalLayout.addWidget(self.loadList)
        self.deleteRbn = QtWidgets.QRadioButton(self.verticalGroupBox)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.deleteRbn.setFont(font)
        self.deleteRbn.setObjectName("deleteRbn")
        self.verticalLayout.addWidget(self.deleteRbn)
        self.deleteList = QtWidgets.QListWidget(self.verticalGroupBox)
        self.deleteList.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.deleteList.setObjectName("deleteList")
        self.verticalLayout.addWidget(self.deleteList)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem4)
        self.deleteBtn = QtWidgets.QPushButton(self.verticalGroupBox)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.deleteBtn.setFont(font)
        self.deleteBtn.setObjectName("deleteBtn")
        self.verticalLayout.addWidget(self.deleteBtn)
        self.startEditorBtn = QtWidgets.QPushButton(self.verticalGroupBox)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.startEditorBtn.setFont(font)
        self.startEditorBtn.setObjectName("startEditorBtn")
        self.verticalLayout.addWidget(self.startEditorBtn)
        self.createNewRbn.raise_()
        self.createFromRbn.raise_()
        self.loadRbn.raise_()
        self.startEditorBtn.raise_()
        self.loadList.raise_()
        self.createFromList.raise_()
        self.deleteRbn.raise_()
        self.deleteList.raise_()
        self.deleteBtn.raise_()
        self.gridLayout_6.addWidget(self.verticalGroupBox, 0, 1, 1, 1)
        self.gridLayout_6.setColumnStretch(0, 1)
        self.gridLayout_6.setColumnStretch(1, 2)
        self.gridLayout_6.setColumnStretch(2, 1)
        self.stackedWidget.addWidget(self.editorPage)
        self.settingsPage = QtWidgets.QWidget()
        self.settingsPage.setObjectName("settingsPage")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.settingsPage)
        self.gridLayout_8.setHorizontalSpacing(6)
        self.gridLayout_8.setVerticalSpacing(15)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_8 = QtWidgets.QLabel(self.settingsPage)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_2.addWidget(self.label_8)
        self.localeCmbBx = QtWidgets.QComboBox(self.settingsPage)
        self.localeCmbBx.setObjectName("localeCmbBx")
        self.horizontalLayout_2.addWidget(self.localeCmbBx)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem5)
        self.gridLayout_8.addLayout(self.horizontalLayout_2, 2, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(5)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_9 = QtWidgets.QLabel(self.settingsPage)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_3.addWidget(self.label_9)
        self.modulesDirLnEd = QtWidgets.QLineEdit(self.settingsPage)
        self.modulesDirLnEd.setObjectName("modulesDirLnEd")
        self.horizontalLayout_3.addWidget(self.modulesDirLnEd)
        self.modulesDirBtn = QtWidgets.QPushButton(self.settingsPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.modulesDirBtn.sizePolicy().hasHeightForWidth())
        self.modulesDirBtn.setSizePolicy(sizePolicy)
        self.modulesDirBtn.setMaximumSize(QtCore.QSize(25, 25))
        self.modulesDirBtn.setObjectName("modulesDirBtn")
        self.horizontalLayout_3.addWidget(self.modulesDirBtn)
        self.gridLayout_8.addLayout(self.horizontalLayout_3, 3, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem6)
        self.applySettingsBtn = QtWidgets.QPushButton(self.settingsPage)
        self.applySettingsBtn.setObjectName("applySettingsBtn")
        self.horizontalLayout_5.addWidget(self.applySettingsBtn)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem7)
        self.cancelSettingsBtn = QtWidgets.QPushButton(self.settingsPage)
        self.cancelSettingsBtn.setObjectName("cancelSettingsBtn")
        self.horizontalLayout_5.addWidget(self.cancelSettingsBtn)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem8)
        self.gridLayout_8.addLayout(self.horizontalLayout_5, 7, 0, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(688, 481, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_8.addItem(spacerItem9, 5, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(5)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_10 = QtWidgets.QLabel(self.settingsPage)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_4.addWidget(self.label_10)
        self.scenarioDirLnEd = QtWidgets.QLineEdit(self.settingsPage)
        self.scenarioDirLnEd.setObjectName("scenarioDirLnEd")
        self.horizontalLayout_4.addWidget(self.scenarioDirLnEd)
        self.scenarioDirBtn = QtWidgets.QPushButton(self.settingsPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scenarioDirBtn.sizePolicy().hasHeightForWidth())
        self.scenarioDirBtn.setSizePolicy(sizePolicy)
        self.scenarioDirBtn.setMaximumSize(QtCore.QSize(25, 25))
        self.scenarioDirBtn.setObjectName("scenarioDirBtn")
        self.horizontalLayout_4.addWidget(self.scenarioDirBtn)
        self.gridLayout_8.addLayout(self.horizontalLayout_4, 4, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.settingsPage)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_8.addWidget(self.label_7, 0, 0, 1, 1)
        self.warningGrBx = QtWidgets.QGroupBox(self.settingsPage)
        self.warningGrBx.setAlignment(QtCore.Qt.AlignCenter)
        self.warningGrBx.setObjectName("warningGrBx")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.warningGrBx)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setSpacing(5)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_6 = QtWidgets.QLabel(self.warningGrBx)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_7.addWidget(self.label_6, 0, 0, 1, 1)
        self.gridLayout_8.addWidget(self.warningGrBx, 6, 0, 1, 1)
        self.stackedWidget.addWidget(self.settingsPage)
        self.gridLayout.addWidget(self.stackedWidget, 0, 1, 1, 1)
        self.gridLayout.setColumnMinimumWidth(0, 200)

        self.retranslateUi(Form)
        self.stackedWidget.setCurrentIndex(5)
        self.createFromRbn.toggled['bool'].connect(self.createFromList.setVisible)
        self.loadRbn.toggled['bool'].connect(self.loadList.setVisible)
        self.deleteRbn.toggled['bool'].connect(self.deleteList.setVisible)
        self.deleteRbn.toggled['bool'].connect(self.deleteBtn.setVisible)
        self.deleteRbn.toggled['bool'].connect(self.startEditorBtn.setHidden)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "MAIN_MENU_LBL"))
        self.scenarioMenuBtn.setText(_translate("Form", "SCENARIOS_MENU"))
        self.editorMenuBtn.setText(_translate("Form", "EDITOR_MENU"))
        self.modulesMenuBtn.setText(_translate("Form", "MODULES_MENU"))
        self.configMenuBtn.setText(_translate("Form", "CONFIG_MENU"))
        self.debugMenuBtn.setText(_translate("Form", "DEBUG_MENU"))
        self.quitMenuBtn.setText(_translate("Form", "QUIT_MENU"))
        self.label_2.setText(_translate("Form", "COMMING_SOON_LBL"))
        self.label_3.setText(_translate("Form", "SCENARIOS_LIST_LBL"))
        self.scenarioListRefreshBtn.setText(_translate("Form", "REFRESH_BTN"))
        self.starScenarioBtn.setText(_translate("Form", "START_BTN"))
        self.optionsEnableChbx.setText(_translate("Form", "ANSWER_OPTIONS"))
        self.label_4.setText(_translate("Form", "MODULES_LBL"))
        self.modulesListRefreshBtn.setText(_translate("Form", "REFRESH_BTN"))
        self.label_5.setText(_translate("Form", "LOGS_LBL"))
        self.createNewRbn.setText(_translate("Form", "CREATE_NEW_MODE"))
        self.createFromRbn.setText(_translate("Form", "CREATE_FROM_MODE"))
        self.loadRbn.setText(_translate("Form", "LOAD_MODE"))
        self.deleteRbn.setText(_translate("Form", "DELETE_MODE"))
        self.deleteBtn.setText(_translate("Form", "DELETE_BTN"))
        self.startEditorBtn.setText(_translate("Form", "START_BTN"))
        self.label_8.setText(_translate("Form", "LANGUAGE_LBL"))
        self.label_9.setText(_translate("Form", "MODULES_DIR_LBL"))
        self.modulesDirBtn.setText(_translate("Form", "..."))
        self.applySettingsBtn.setText(_translate("Form", "APPLY_BTN"))
        self.cancelSettingsBtn.setText(_translate("Form", "CANCEL_BTN"))
        self.label_10.setText(_translate("Form", "SCENARIO_DIR_LBL"))
        self.scenarioDirBtn.setText(_translate("Form", "..."))
        self.label_7.setText(_translate("Form", "SETTINGS_LBL"))
        self.warningGrBx.setTitle(_translate("Form", "WARNING_TEXT"))
        self.label_6.setText(_translate("Form", "SETTINGS_NOT_APPLY_TEXT"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
