# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Repositories\lang_tutor\ui\main\main_view.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1024, 768)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.menuLayout = QtWidgets.QVBoxLayout()
        self.menuLayout.setSpacing(15)
        self.menuLayout.setObjectName("menuLayout")
        self.label = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.menuLayout.addWidget(self.label)
        self.scenarioMenuBtn = QtWidgets.QPushButton(Form)
        self.scenarioMenuBtn.setCheckable(False)
        self.scenarioMenuBtn.setObjectName("scenarioMenuBtn")
        self.menuLayout.addWidget(self.scenarioMenuBtn)
        self.editorMenuBtn = QtWidgets.QPushButton(Form)
        self.editorMenuBtn.setEnabled(True)
        self.editorMenuBtn.setObjectName("editorMenuBtn")
        self.menuLayout.addWidget(self.editorMenuBtn)
        self.modulesMenuBtn = QtWidgets.QPushButton(Form)
        self.modulesMenuBtn.setCheckable(False)
        self.modulesMenuBtn.setObjectName("modulesMenuBtn")
        self.menuLayout.addWidget(self.modulesMenuBtn)
        self.configMenuBtn = QtWidgets.QPushButton(Form)
        self.configMenuBtn.setEnabled(False)
        self.configMenuBtn.setObjectName("configMenuBtn")
        self.menuLayout.addWidget(self.configMenuBtn)
        self.debugMenuBtn = QtWidgets.QPushButton(Form)
        self.debugMenuBtn.setObjectName("debugMenuBtn")
        self.menuLayout.addWidget(self.debugMenuBtn)
        self.quitMenuBtn = QtWidgets.QPushButton(Form)
        self.quitMenuBtn.setObjectName("quitMenuBtn")
        self.menuLayout.addWidget(self.quitMenuBtn)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.menuLayout.addItem(spacerItem)
        self.gridLayout.addLayout(self.menuLayout, 0, 0, 1, 1)
        self.stackedWidget = QtWidgets.QStackedWidget(Form)
        self.stackedWidget.setObjectName("stackedWidget")
        self.commingSoonPage = QtWidgets.QWidget()
        self.commingSoonPage.setObjectName("commingSoonPage")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.commingSoonPage)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_2 = QtWidgets.QLabel(self.commingSoonPage)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.commingSoonPage)
        self.scenarioPage = QtWidgets.QWidget()
        self.scenarioPage.setObjectName("scenarioPage")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.scenarioPage)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_3 = QtWidgets.QLabel(self.scenarioPage)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 0, 1, 1)
        self.scenarioListRefreshBtn = QtWidgets.QPushButton(self.scenarioPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scenarioListRefreshBtn.sizePolicy().hasHeightForWidth())
        self.scenarioListRefreshBtn.setSizePolicy(sizePolicy)
        self.scenarioListRefreshBtn.setMinimumSize(QtCore.QSize(125, 25))
        self.scenarioListRefreshBtn.setObjectName("scenarioListRefreshBtn")
        self.gridLayout_2.addWidget(self.scenarioListRefreshBtn, 0, 1, 1, 1)
        self.scenarioList = QtWidgets.QListWidget(self.scenarioPage)
        self.scenarioList.setObjectName("scenarioList")
        self.gridLayout_2.addWidget(self.scenarioList, 1, 0, 1, 2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.starScenarioBtn = QtWidgets.QPushButton(self.scenarioPage)
        self.starScenarioBtn.setObjectName("starScenarioBtn")
        self.horizontalLayout.addWidget(self.starScenarioBtn)
        self.optionsEnableChbx = QtWidgets.QCheckBox(self.scenarioPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.optionsEnableChbx.sizePolicy().hasHeightForWidth())
        self.optionsEnableChbx.setSizePolicy(sizePolicy)
        self.optionsEnableChbx.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.optionsEnableChbx.setObjectName("optionsEnableChbx")
        self.horizontalLayout.addWidget(self.optionsEnableChbx)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 1)
        self.horizontalLayout.setStretch(2, 1)
        self.gridLayout_2.addLayout(self.horizontalLayout, 2, 0, 1, 2)
        self.stackedWidget.addWidget(self.scenarioPage)
        self.modulesPage = QtWidgets.QWidget()
        self.modulesPage.setObjectName("modulesPage")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.modulesPage)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_4 = QtWidgets.QLabel(self.modulesPage)
        self.label_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_4.addWidget(self.label_4, 0, 0, 1, 1)
        self.modulesListRefreshBtn = QtWidgets.QPushButton(self.modulesPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.modulesListRefreshBtn.sizePolicy().hasHeightForWidth())
        self.modulesListRefreshBtn.setSizePolicy(sizePolicy)
        self.modulesListRefreshBtn.setMinimumSize(QtCore.QSize(125, 25))
        self.modulesListRefreshBtn.setObjectName("modulesListRefreshBtn")
        self.gridLayout_4.addWidget(self.modulesListRefreshBtn, 0, 1, 1, 1)
        self.modulesList = QtWidgets.QListWidget(self.modulesPage)
        self.modulesList.setObjectName("modulesList")
        self.gridLayout_4.addWidget(self.modulesList, 3, 0, 1, 2)
        self.stackedWidget.addWidget(self.modulesPage)
        self.debugPage = QtWidgets.QWidget()
        self.debugPage.setObjectName("debugPage")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.debugPage)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.logPte = QtWidgets.QPlainTextEdit(self.debugPage)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.logPte.setFont(font)
        self.logPte.setReadOnly(True)
        self.logPte.setPlainText("")
        self.logPte.setObjectName("logPte")
        self.gridLayout_5.addWidget(self.logPte, 1, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.debugPage)
        self.label_5.setObjectName("label_5")
        self.gridLayout_5.addWidget(self.label_5, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.debugPage)
        self.editorPage = QtWidgets.QWidget()
        self.editorPage.setObjectName("editorPage")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.editorPage)
        self.gridLayout_6.setContentsMargins(-1, 50, -1, 100)
        self.gridLayout_6.setObjectName("gridLayout_6")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem2, 0, 2, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem3, 0, 0, 1, 1)
        self.verticalGroupBox = QtWidgets.QGroupBox(self.editorPage)
        self.verticalGroupBox.setObjectName("verticalGroupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalGroupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.createNewRbn = QtWidgets.QRadioButton(self.verticalGroupBox)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.createNewRbn.setFont(font)
        self.createNewRbn.setChecked(True)
        self.createNewRbn.setObjectName("createNewRbn")
        self.verticalLayout.addWidget(self.createNewRbn)
        self.createFromRbn = QtWidgets.QRadioButton(self.verticalGroupBox)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.createFromRbn.setFont(font)
        self.createFromRbn.setObjectName("createFromRbn")
        self.verticalLayout.addWidget(self.createFromRbn)
        self.createFromList = QtWidgets.QListWidget(self.verticalGroupBox)
        self.createFromList.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.createFromList.setObjectName("createFromList")
        self.verticalLayout.addWidget(self.createFromList)
        self.loadRbn = QtWidgets.QRadioButton(self.verticalGroupBox)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.loadRbn.setFont(font)
        self.loadRbn.setObjectName("loadRbn")
        self.verticalLayout.addWidget(self.loadRbn)
        self.loadList = QtWidgets.QListWidget(self.verticalGroupBox)
        self.loadList.setObjectName("loadList")
        self.verticalLayout.addWidget(self.loadList)
        self.deleteRbn = QtWidgets.QRadioButton(self.verticalGroupBox)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.deleteRbn.setFont(font)
        self.deleteRbn.setObjectName("deleteRbn")
        self.verticalLayout.addWidget(self.deleteRbn)
        self.deleteList = QtWidgets.QListWidget(self.verticalGroupBox)
        self.deleteList.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.deleteList.setObjectName("deleteList")
        self.verticalLayout.addWidget(self.deleteList)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem4)
        self.deleteBtn = QtWidgets.QPushButton(self.verticalGroupBox)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.deleteBtn.setFont(font)
        self.deleteBtn.setObjectName("deleteBtn")
        self.verticalLayout.addWidget(self.deleteBtn)
        self.startEditorBtn = QtWidgets.QPushButton(self.verticalGroupBox)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.startEditorBtn.setFont(font)
        self.startEditorBtn.setObjectName("startEditorBtn")
        self.verticalLayout.addWidget(self.startEditorBtn)
        self.createNewRbn.raise_()
        self.createFromRbn.raise_()
        self.loadRbn.raise_()
        self.startEditorBtn.raise_()
        self.loadList.raise_()
        self.createFromList.raise_()
        self.deleteRbn.raise_()
        self.deleteList.raise_()
        self.deleteBtn.raise_()
        self.gridLayout_6.addWidget(self.verticalGroupBox, 0, 1, 1, 1)
        self.gridLayout_6.setColumnStretch(0, 1)
        self.gridLayout_6.setColumnStretch(1, 2)
        self.gridLayout_6.setColumnStretch(2, 1)
        self.stackedWidget.addWidget(self.editorPage)
        self.gridLayout.addWidget(self.stackedWidget, 0, 1, 1, 1)
        self.gridLayout.setColumnMinimumWidth(0, 200)

        self.retranslateUi(Form)
        self.stackedWidget.setCurrentIndex(4)
        self.createFromRbn.toggled['bool'].connect(self.createFromList.setVisible)
        self.loadRbn.toggled['bool'].connect(self.loadList.setVisible)
        self.deleteRbn.toggled['bool'].connect(self.deleteList.setVisible)
        self.deleteRbn.toggled['bool'].connect(self.deleteBtn.setVisible)
        self.deleteRbn.toggled['bool'].connect(self.startEditorBtn.setHidden)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "MAIN_MENU_LBL"))
        self.scenarioMenuBtn.setText(_translate("Form", "SCENARIOS_MENU"))
        self.editorMenuBtn.setText(_translate("Form", "EDITOR_MENU"))
        self.modulesMenuBtn.setText(_translate("Form", "MODULES_MENU"))
        self.configMenuBtn.setText(_translate("Form", "CONFIG_MENU"))
        self.debugMenuBtn.setText(_translate("Form", "DEBUG_MENU"))
        self.quitMenuBtn.setText(_translate("Form", "QUIT_MENU"))
        self.label_2.setText(_translate("Form", "COMMING_SOON_LBL"))
        self.label_3.setText(_translate("Form", "SCENARIOS_LIST_LBL"))
        self.scenarioListRefreshBtn.setText(_translate("Form", "REFRESH_BTN"))
        self.starScenarioBtn.setText(_translate("Form", "START_BTN"))
        self.optionsEnableChbx.setText(_translate("Form", "ANSWER_OPTIONS"))
        self.label_4.setText(_translate("Form", "MODULES_LBL"))
        self.modulesListRefreshBtn.setText(_translate("Form", "REFRESH_BTN"))
        self.label_5.setText(_translate("Form", "LOGS_LBL"))
        self.createNewRbn.setText(_translate("Form", "CREATE_NEW_MODE"))
        self.createFromRbn.setText(_translate("Form", "CREATE_FROM_MODE"))
        self.loadRbn.setText(_translate("Form", "LOAD_MODE"))
        self.deleteRbn.setText(_translate("Form", "DELETE_MODE"))
        self.deleteBtn.setText(_translate("Form", "DELETE_BTN"))
        self.startEditorBtn.setText(_translate("Form", "START_BTN"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
