# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Repositories\lang_tutor\ui\main_view.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1024, 768)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(1024, 768))
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.menuLayout = QtWidgets.QVBoxLayout()
        self.menuLayout.setSpacing(15)
        self.menuLayout.setObjectName("menuLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.menuLayout.addWidget(self.label)
        self.scenarioMenuBtn = QtWidgets.QPushButton(self.centralwidget)
        self.scenarioMenuBtn.setCheckable(False)
        self.scenarioMenuBtn.setObjectName("scenarioMenuBtn")
        self.menuLayout.addWidget(self.scenarioMenuBtn)
        self.editorMenuBtn = QtWidgets.QPushButton(self.centralwidget)
        self.editorMenuBtn.setEnabled(False)
        self.editorMenuBtn.setObjectName("editorMenuBtn")
        self.menuLayout.addWidget(self.editorMenuBtn)
        self.modulesMenuBtn = QtWidgets.QPushButton(self.centralwidget)
        self.modulesMenuBtn.setCheckable(False)
        self.modulesMenuBtn.setObjectName("modulesMenuBtn")
        self.menuLayout.addWidget(self.modulesMenuBtn)
        self.configMenuBtn = QtWidgets.QPushButton(self.centralwidget)
        self.configMenuBtn.setEnabled(False)
        self.configMenuBtn.setObjectName("configMenuBtn")
        self.menuLayout.addWidget(self.configMenuBtn)
        self.debugMenuBtn = QtWidgets.QPushButton(self.centralwidget)
        self.debugMenuBtn.setObjectName("debugMenuBtn")
        self.menuLayout.addWidget(self.debugMenuBtn)
        self.quitMenuBtn = QtWidgets.QPushButton(self.centralwidget)
        self.quitMenuBtn.setObjectName("quitMenuBtn")
        self.menuLayout.addWidget(self.quitMenuBtn)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.menuLayout.addItem(spacerItem)
        self.gridLayout.addLayout(self.menuLayout, 0, 0, 1, 1)
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.commingSoonPage = QtWidgets.QWidget()
        self.commingSoonPage.setObjectName("commingSoonPage")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.commingSoonPage)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_2 = QtWidgets.QLabel(self.commingSoonPage)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.commingSoonPage)
        self.scenarioPage = QtWidgets.QWidget()
        self.scenarioPage.setObjectName("scenarioPage")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.scenarioPage)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_3 = QtWidgets.QLabel(self.scenarioPage)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 0, 1, 1)
        self.starScenarioBtn = QtWidgets.QPushButton(self.scenarioPage)
        self.starScenarioBtn.setObjectName("starScenarioBtn")
        self.gridLayout_2.addWidget(self.starScenarioBtn, 2, 0, 1, 2)
        self.scenarioListRefreshBtn = QtWidgets.QPushButton(self.scenarioPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scenarioListRefreshBtn.sizePolicy().hasHeightForWidth())
        self.scenarioListRefreshBtn.setSizePolicy(sizePolicy)
        self.scenarioListRefreshBtn.setMaximumSize(QtCore.QSize(25, 25))
        self.scenarioListRefreshBtn.setObjectName("scenarioListRefreshBtn")
        self.gridLayout_2.addWidget(self.scenarioListRefreshBtn, 0, 1, 1, 1)
        self.scenarioList = QtWidgets.QListWidget(self.scenarioPage)
        self.scenarioList.setObjectName("scenarioList")
        self.gridLayout_2.addWidget(self.scenarioList, 1, 0, 1, 2)
        self.stackedWidget.addWidget(self.scenarioPage)
        self.modulesPage = QtWidgets.QWidget()
        self.modulesPage.setObjectName("modulesPage")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.modulesPage)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_4 = QtWidgets.QLabel(self.modulesPage)
        self.label_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_4.addWidget(self.label_4, 0, 0, 1, 1)
        self.modulesListRefreshBtn = QtWidgets.QPushButton(self.modulesPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.modulesListRefreshBtn.sizePolicy().hasHeightForWidth())
        self.modulesListRefreshBtn.setSizePolicy(sizePolicy)
        self.modulesListRefreshBtn.setMaximumSize(QtCore.QSize(25, 25))
        self.modulesListRefreshBtn.setObjectName("modulesListRefreshBtn")
        self.gridLayout_4.addWidget(self.modulesListRefreshBtn, 0, 1, 1, 1)
        self.modulesList = QtWidgets.QListWidget(self.modulesPage)
        self.modulesList.setObjectName("modulesList")
        self.gridLayout_4.addWidget(self.modulesList, 3, 0, 1, 2)
        self.stackedWidget.addWidget(self.modulesPage)
        self.debugPage = QtWidgets.QWidget()
        self.debugPage.setObjectName("debugPage")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.debugPage)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.logPte = QtWidgets.QPlainTextEdit(self.debugPage)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.logPte.setFont(font)
        self.logPte.setReadOnly(True)
        self.logPte.setPlainText("")
        self.logPte.setObjectName("logPte")
        self.gridLayout_5.addWidget(self.logPte, 1, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.debugPage)
        self.label_5.setObjectName("label_5")
        self.gridLayout_5.addWidget(self.label_5, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.debugPage)
        self.gridLayout.addWidget(self.stackedWidget, 0, 1, 1, 1)
        self.gridLayout.setColumnMinimumWidth(0, 200)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(1)
        self.quitMenuBtn.clicked.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.scenarioMenuBtn, self.editorMenuBtn)
        MainWindow.setTabOrder(self.editorMenuBtn, self.modulesMenuBtn)
        MainWindow.setTabOrder(self.modulesMenuBtn, self.configMenuBtn)
        MainWindow.setTabOrder(self.configMenuBtn, self.debugMenuBtn)
        MainWindow.setTabOrder(self.debugMenuBtn, self.quitMenuBtn)
        MainWindow.setTabOrder(self.quitMenuBtn, self.logPte)
        MainWindow.setTabOrder(self.logPte, self.starScenarioBtn)
        MainWindow.setTabOrder(self.starScenarioBtn, self.modulesList)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Lang tutor"))
        self.label.setText(_translate("MainWindow", "Main menu"))
        self.scenarioMenuBtn.setText(_translate("MainWindow", "Scenarios"))
        self.editorMenuBtn.setText(_translate("MainWindow", "Editor"))
        self.modulesMenuBtn.setText(_translate("MainWindow", "Modules"))
        self.configMenuBtn.setText(_translate("MainWindow", "Config"))
        self.debugMenuBtn.setText(_translate("MainWindow", "Debug"))
        self.quitMenuBtn.setText(_translate("MainWindow", "Quit"))
        self.label_2.setText(_translate("MainWindow", "Comming soon"))
        self.label_3.setText(_translate("MainWindow", "Scenarios list"))
        self.starScenarioBtn.setText(_translate("MainWindow", "Start"))
        self.scenarioListRefreshBtn.setText(_translate("MainWindow", "R"))
        self.label_4.setText(_translate("MainWindow", "Modules"))
        self.modulesListRefreshBtn.setText(_translate("MainWindow", "R"))
        self.label_5.setText(_translate("MainWindow", "Logs"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
